<template>
   <div class="Records">
       <div>
            <h1>平台数据（截止至2019-07-26 23:59:59）</h1>
            <div>
                <p>平台自成立以来的累计交易金额</p>
                <strong>53.078.959.523.6元</strong>
                <span>累计交易笔数:4.470.469笔</span>
            </div>
            <div>
                <span>理财余额</span>
                <strong>3.084.793.754.51元</strong>
                <ul>
                    <li>
                        <p>累计理财人数量</p>
                        <strong>599.775人</strong>
                    </li>
                     <li>
                        <p>累计投资人数量</p>
                        <strong>1.084.741人</strong>
                    </li>
                     <li>
                        <p>当前理财人数量</p>
                        <strong>37.784人</strong>
                    </li>
                     <li>
                        <p>当前投资人数量</p>
                        <strong>55.044人</strong>
                    </li>
                </ul>
            </div>
       </div>
        <div>
            <h1>收费标准</h1>
            <div>
                <h2>基础业务收费标准</h2>
                <ul>
                    <li><span>业务类型:</span><i>资费标准</i></li>
                    <li><span>用户注册:</span><i>免费</i></li>
                    <li><span>开通存管账户:</span><i>免费</i></li>
                    <li><span>充值:</span><i>免费</i></li>
                    <li><span>提现:</span><i>1元/笔（目前免费）</i></li>
                </ul>
            </div>
            <div>
                <h2>授权投标业务收费标准</h2>
                <p>包含授权投标、工作定投、梦想计划、日进斗金、至尊宝</p>
                <p><span>加入费用:</span><i>除出借本金外，无其他额外费用</i></p>
                <p><span>授权结束费用:</span><i>无</i></p>
            </div>
            <div>
                <h2>管理费用:</h2>
                <p>当前实际利息-目标利息，服务费为0元；</p>
                <p>当前实际利息-目标利息，则服务费=实；</p>
                <p>利息-目标利息</p>
            </div>
            <div>
                <h2>提前退出违约费:</h2>
                <p>不支持提前转让</p>
            </div>
            <div>
                <h2>目标利息:</h2>
                <span>定投和梦想计划的目标利息=[R*(X+M)*30/365]+[R*(X+2M)*30/365]......+[(N-1)*R*Y*30/365](R:每月加入本金，X:平均出借利息，N:锁定期，M:每次成功划扣利息，Y:最高封顶平均出借利息)</span>
            </div>
            <div>
                <h2>直投项目及债权转让业务收费标准</h2>
                <p><span>加入费用:</span><i>除出借本金外，无其他额外费用</i></p>
                <p><span>债权转让手续费:</span><i>根据债权持有天数不同手续费施行剃式扣费</i></p>
            </div>
        </div>
   </div>
</template>

<script>
    export default {
       
    }
</script>

<style>

</style>